# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e3d9ffb7610e3bdb519644654a0233950a0e1071867a0da93261954f9cc6f4fc1b48601a0eec2a2e3f2c9d0dacc00419df700a43bd86f85e1b4de29cf4eb6bf

test:
  secret_key_base: 74b0d5bd48187d416e0d357c0119e6c565913f378b46aaee8a51203d0e2dcb2c2405ed0a8b340846e42740684ffa542d51f3cfb796f3d5b9d52db1c140a9a523

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
